# -*- coding: utf-8 -*-
"""TTS 4 (no 4 dan 5)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OsE2MAOG8TxIW2X8GE7s6eVj85PQEjfL
"""

def kelola_daftar_tugas():
    daftar_tugas = []
    try:
        jumlah_dibeli = float(input("Masukkan jumlah bahan baku (kg/unit): "))
        harga_per_unit = float(input("Masukkan harga per unit (Rp): "))
        biaya_angkut = float(input("Masukkan biaya transportasi/pengiriman (Rp): "))
        biaya_penanganan = float(input("Masukkan biaya penanganan/bongkar muat (Rp): "))
        persen_penyusutan = float(input("Masukkan estimasi persentase penyusutan/penyortiran (%): "))
    except ValueError:
        print("Input harus berupa angka.")
        return

    # Perhitungan dasar
    harga_pembelian_kotor = jumlah_dibeli * harga_per_unit
    total_biaya_tambahan = biaya_angkut + biaya_penanganan

    # Perhitungan penyusutan (bahan yang hilang/rusak)
    jumlah_hilang = jumlah_dibeli * (persen_penyusutan / 100)
    jumlah_efektif = jumlah_dibeli - jumlah_hilang

    # Total biaya modal
    total_biaya_keseluruhan = harga_pembelian_kotor + total_biaya_tambahan

    # Harga pokok per unit yang siap dipakai (berdasarkan jumlah efektif)
    if jumlah_efektif > 0:
        harga_pokok_efektif_per_unit = total_biaya_keseluruhan / jumlah_efektif
    else:
        harga_pokok_efektif_per_unit = 0

    # Menampilkan hasil
    print("\n" + "="*40)
    print(f" RINCIAN BIAYA BAHAN BAKU: {nama_bahan.upper()}")
    print("="*40)
    print(f"Total Pembelian Kotor   : Rp {harga_pembelian_kotor:,.2f}")
    print(f"Total Biaya Operasional : Rp {total_biaya_tambahan:,.2f}")
    print(f"Total Biaya Keseluruhan : Rp {total_biaya_keseluruhan:,.2f}")
    print("-" * 40)
    print(f"Jumlah Dibeli           : {jumlah_dibeli:.2f} kg/unit")
    print(f"Jumlah Menyusut/Rusak   : {jumlah_hilang:.2f} kg/unit ({persen_penyusutan}%)")
    print(f"Jumlah Efektif Layak Pakai: {jumlah_efektif:.2f} kg/unit")
    print("-" * 40)
    print(f"HPP Bahan Baku (Real)   : Rp {harga_pokok_efektif_per_unit:,.2f} / kg")
    print("="*80)

# Jalankan fungsi
hitung_harga_bahan_baku()
