# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPmpuNPgtt2Tkz0Q9DNL-K_3J3ttr4Jw
"""

# Program Harga Jual Produk Agroindustri

print("=== PROGRAM HARGA JUAL PRODUK AGROINDUSTRI ===")

nama_produk = input("Nama produk: ")
jumlah_produksi = int(input("Jumlah produksi (unit): "))
biaya_bahan = float(input("Biaya bahan baku (Rp): "))
biaya_tenaga = float(input("Biaya tenaga kerja (Rp): "))
biaya_lain = float(input("Biaya lain-lain (Rp): "))
persentase_keuntungan = float(input("Keuntungan yang diinginkan (%): "))

# Menghitung total biaya produksi
total_biaya = biaya_bahan + biaya_tenaga + biaya_lain

# Menghitung biaya produksi per unit
biaya_per_unit = total_biaya / jumlah_produksi

# Menghitung keuntungan per unit
keuntungan = biaya_per_unit * persentase_keuntungan / 100

# Menghitung harga jual per unit
harga_jual = biaya_per_unit + keuntungan

# Menampilkan laporan
print("\n=== LAPORAN HARGA JUAL ===")
print("Nama produk          :", nama_produk)
print("Jumlah produksi      :", jumlah_produksi, "unit")
print("Total biaya produksi : Rp", total_biaya)
print("Biaya per unit       : Rp", biaya_per_unit)
print("Keuntungan per unit  : Rp", keuntungan)
print("Harga jual per unit  : Rp", harga_jual)